// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-backend/internal/ent/authorize"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AuthorizeCreate is the builder for creating a Authorize entity.
type AuthorizeCreate struct {
	config
	mutation *AuthorizeMutation
	hooks    []Hook
}

// SetJwtToken sets the "jwt_token" field.
func (ac *AuthorizeCreate) SetJwtToken(s string) *AuthorizeCreate {
	ac.mutation.SetJwtToken(s)
	return ac
}

// SetNillableJwtToken sets the "jwt_token" field if the given value is not nil.
func (ac *AuthorizeCreate) SetNillableJwtToken(s *string) *AuthorizeCreate {
	if s != nil {
		ac.SetJwtToken(*s)
	}
	return ac
}

// SetToken sets the "token" field.
func (ac *AuthorizeCreate) SetToken(s string) *AuthorizeCreate {
	ac.mutation.SetToken(s)
	return ac
}

// SetID sets the "id" field.
func (ac *AuthorizeCreate) SetID(u uuid.UUID) *AuthorizeCreate {
	ac.mutation.SetID(u)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *AuthorizeCreate) SetNillableID(u *uuid.UUID) *AuthorizeCreate {
	if u != nil {
		ac.SetID(*u)
	}
	return ac
}

// Mutation returns the AuthorizeMutation object of the builder.
func (ac *AuthorizeCreate) Mutation() *AuthorizeMutation {
	return ac.mutation
}

// Save creates the Authorize in the database.
func (ac *AuthorizeCreate) Save(ctx context.Context) (*Authorize, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AuthorizeCreate) SaveX(ctx context.Context) *Authorize {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AuthorizeCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AuthorizeCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AuthorizeCreate) defaults() {
	if _, ok := ac.mutation.ID(); !ok {
		v := authorize.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AuthorizeCreate) check() error {
	if v, ok := ac.mutation.JwtToken(); ok {
		if err := authorize.JwtTokenValidator(v); err != nil {
			return &ValidationError{Name: "jwt_token", err: fmt.Errorf(`ent: validator failed for field "Authorize.jwt_token": %w`, err)}
		}
	}
	if _, ok := ac.mutation.Token(); !ok {
		return &ValidationError{Name: "token", err: errors.New(`ent: missing required field "Authorize.token"`)}
	}
	if v, ok := ac.mutation.Token(); ok {
		if err := authorize.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Authorize.token": %w`, err)}
		}
	}
	return nil
}

func (ac *AuthorizeCreate) sqlSave(ctx context.Context) (*Authorize, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AuthorizeCreate) createSpec() (*Authorize, *sqlgraph.CreateSpec) {
	var (
		_node = &Authorize{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(authorize.Table, sqlgraph.NewFieldSpec(authorize.FieldID, field.TypeUUID))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ac.mutation.JwtToken(); ok {
		_spec.SetField(authorize.FieldJwtToken, field.TypeString, value)
		_node.JwtToken = value
	}
	if value, ok := ac.mutation.Token(); ok {
		_spec.SetField(authorize.FieldToken, field.TypeString, value)
		_node.Token = value
	}
	return _node, _spec
}

// AuthorizeCreateBulk is the builder for creating many Authorize entities in bulk.
type AuthorizeCreateBulk struct {
	config
	err      error
	builders []*AuthorizeCreate
}

// Save creates the Authorize entities in the database.
func (acb *AuthorizeCreateBulk) Save(ctx context.Context) ([]*Authorize, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Authorize, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AuthorizeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AuthorizeCreateBulk) SaveX(ctx context.Context) []*Authorize {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AuthorizeCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AuthorizeCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
