// Code generated by ent, DO NOT EDIT.

package authorize

import (
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the authorize type in the database.
	Label = "authorize"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldJwtToken holds the string denoting the jwt_token field in the database.
	FieldJwtToken = "jwt_token"
	// FieldToken holds the string denoting the token field in the database.
	FieldToken = "token"
	// Table holds the table name of the authorize in the database.
	Table = "authorizes"
)

// Columns holds all SQL columns for authorize fields.
var Columns = []string{
	FieldID,
	FieldJwtToken,
	FieldToken,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// JwtTokenValidator is a validator for the "jwt_token" field. It is called by the builders before save.
	JwtTokenValidator func(string) error
	// TokenValidator is a validator for the "token" field. It is called by the builders before save.
	TokenValidator func(string) error
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Authorize queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByJwtToken orders the results by the jwt_token field.
func ByJwtToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldJwtToken, opts...).ToFunc()
}

// ByToken orders the results by the token field.
func ByToken(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldToken, opts...).ToFunc()
}
