// Code generated by ent, DO NOT EDIT.

package authorize

import (
	"chat-backend/internal/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Authorize {
	return predicate.Authorize(sql.FieldLTE(FieldID, id))
}

// JwtToken applies equality check predicate on the "jwt_token" field. It's identical to JwtTokenEQ.
func JwtToken(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldEQ(FieldJwtToken, v))
}

// Token applies equality check predicate on the "token" field. It's identical to TokenEQ.
func Token(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldEQ(FieldToken, v))
}

// JwtTokenEQ applies the EQ predicate on the "jwt_token" field.
func JwtTokenEQ(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldEQ(FieldJwtToken, v))
}

// JwtTokenNEQ applies the NEQ predicate on the "jwt_token" field.
func JwtTokenNEQ(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldNEQ(FieldJwtToken, v))
}

// JwtTokenIn applies the In predicate on the "jwt_token" field.
func JwtTokenIn(vs ...string) predicate.Authorize {
	return predicate.Authorize(sql.FieldIn(FieldJwtToken, vs...))
}

// JwtTokenNotIn applies the NotIn predicate on the "jwt_token" field.
func JwtTokenNotIn(vs ...string) predicate.Authorize {
	return predicate.Authorize(sql.FieldNotIn(FieldJwtToken, vs...))
}

// JwtTokenGT applies the GT predicate on the "jwt_token" field.
func JwtTokenGT(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldGT(FieldJwtToken, v))
}

// JwtTokenGTE applies the GTE predicate on the "jwt_token" field.
func JwtTokenGTE(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldGTE(FieldJwtToken, v))
}

// JwtTokenLT applies the LT predicate on the "jwt_token" field.
func JwtTokenLT(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldLT(FieldJwtToken, v))
}

// JwtTokenLTE applies the LTE predicate on the "jwt_token" field.
func JwtTokenLTE(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldLTE(FieldJwtToken, v))
}

// JwtTokenContains applies the Contains predicate on the "jwt_token" field.
func JwtTokenContains(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldContains(FieldJwtToken, v))
}

// JwtTokenHasPrefix applies the HasPrefix predicate on the "jwt_token" field.
func JwtTokenHasPrefix(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldHasPrefix(FieldJwtToken, v))
}

// JwtTokenHasSuffix applies the HasSuffix predicate on the "jwt_token" field.
func JwtTokenHasSuffix(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldHasSuffix(FieldJwtToken, v))
}

// JwtTokenIsNil applies the IsNil predicate on the "jwt_token" field.
func JwtTokenIsNil() predicate.Authorize {
	return predicate.Authorize(sql.FieldIsNull(FieldJwtToken))
}

// JwtTokenNotNil applies the NotNil predicate on the "jwt_token" field.
func JwtTokenNotNil() predicate.Authorize {
	return predicate.Authorize(sql.FieldNotNull(FieldJwtToken))
}

// JwtTokenEqualFold applies the EqualFold predicate on the "jwt_token" field.
func JwtTokenEqualFold(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldEqualFold(FieldJwtToken, v))
}

// JwtTokenContainsFold applies the ContainsFold predicate on the "jwt_token" field.
func JwtTokenContainsFold(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldContainsFold(FieldJwtToken, v))
}

// TokenEQ applies the EQ predicate on the "token" field.
func TokenEQ(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldEQ(FieldToken, v))
}

// TokenNEQ applies the NEQ predicate on the "token" field.
func TokenNEQ(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldNEQ(FieldToken, v))
}

// TokenIn applies the In predicate on the "token" field.
func TokenIn(vs ...string) predicate.Authorize {
	return predicate.Authorize(sql.FieldIn(FieldToken, vs...))
}

// TokenNotIn applies the NotIn predicate on the "token" field.
func TokenNotIn(vs ...string) predicate.Authorize {
	return predicate.Authorize(sql.FieldNotIn(FieldToken, vs...))
}

// TokenGT applies the GT predicate on the "token" field.
func TokenGT(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldGT(FieldToken, v))
}

// TokenGTE applies the GTE predicate on the "token" field.
func TokenGTE(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldGTE(FieldToken, v))
}

// TokenLT applies the LT predicate on the "token" field.
func TokenLT(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldLT(FieldToken, v))
}

// TokenLTE applies the LTE predicate on the "token" field.
func TokenLTE(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldLTE(FieldToken, v))
}

// TokenContains applies the Contains predicate on the "token" field.
func TokenContains(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldContains(FieldToken, v))
}

// TokenHasPrefix applies the HasPrefix predicate on the "token" field.
func TokenHasPrefix(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldHasPrefix(FieldToken, v))
}

// TokenHasSuffix applies the HasSuffix predicate on the "token" field.
func TokenHasSuffix(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldHasSuffix(FieldToken, v))
}

// TokenEqualFold applies the EqualFold predicate on the "token" field.
func TokenEqualFold(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldEqualFold(FieldToken, v))
}

// TokenContainsFold applies the ContainsFold predicate on the "token" field.
func TokenContainsFold(v string) predicate.Authorize {
	return predicate.Authorize(sql.FieldContainsFold(FieldToken, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Authorize) predicate.Authorize {
	return predicate.Authorize(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Authorize) predicate.Authorize {
	return predicate.Authorize(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Authorize) predicate.Authorize {
	return predicate.Authorize(sql.NotPredicates(p))
}
