// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-service/internal/ent/predicate"
	"chat-service/internal/ent/room"
	"chat-service/internal/ent/roominfo"
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// RoomInfoQuery is the builder for querying RoomInfo entities.
type RoomInfoQuery struct {
	config
	ctx        *QueryContext
	order      []roominfo.OrderOption
	inters     []Interceptor
	predicates []predicate.RoomInfo
	withRooms  *RoomQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoomInfoQuery builder.
func (riq *RoomInfoQuery) Where(ps ...predicate.RoomInfo) *RoomInfoQuery {
	riq.predicates = append(riq.predicates, ps...)
	return riq
}

// Limit the number of records to be returned by this query.
func (riq *RoomInfoQuery) Limit(limit int) *RoomInfoQuery {
	riq.ctx.Limit = &limit
	return riq
}

// Offset to start from.
func (riq *RoomInfoQuery) Offset(offset int) *RoomInfoQuery {
	riq.ctx.Offset = &offset
	return riq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (riq *RoomInfoQuery) Unique(unique bool) *RoomInfoQuery {
	riq.ctx.Unique = &unique
	return riq
}

// Order specifies how the records should be ordered.
func (riq *RoomInfoQuery) Order(o ...roominfo.OrderOption) *RoomInfoQuery {
	riq.order = append(riq.order, o...)
	return riq
}

// QueryRooms chains the current query on the "rooms" edge.
func (riq *RoomInfoQuery) QueryRooms() *RoomQuery {
	query := (&RoomClient{config: riq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := riq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := riq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roominfo.Table, roominfo.FieldID, selector),
			sqlgraph.To(room.Table, room.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, roominfo.RoomsTable, roominfo.RoomsColumn),
		)
		fromU = sqlgraph.SetNeighbors(riq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoomInfo entity from the query.
// Returns a *NotFoundError when no RoomInfo was found.
func (riq *RoomInfoQuery) First(ctx context.Context) (*RoomInfo, error) {
	nodes, err := riq.Limit(1).All(setContextOp(ctx, riq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roominfo.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (riq *RoomInfoQuery) FirstX(ctx context.Context) *RoomInfo {
	node, err := riq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoomInfo ID from the query.
// Returns a *NotFoundError when no RoomInfo ID was found.
func (riq *RoomInfoQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = riq.Limit(1).IDs(setContextOp(ctx, riq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roominfo.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (riq *RoomInfoQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := riq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoomInfo entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoomInfo entity is found.
// Returns a *NotFoundError when no RoomInfo entities are found.
func (riq *RoomInfoQuery) Only(ctx context.Context) (*RoomInfo, error) {
	nodes, err := riq.Limit(2).All(setContextOp(ctx, riq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roominfo.Label}
	default:
		return nil, &NotSingularError{roominfo.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (riq *RoomInfoQuery) OnlyX(ctx context.Context) *RoomInfo {
	node, err := riq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoomInfo ID in the query.
// Returns a *NotSingularError when more than one RoomInfo ID is found.
// Returns a *NotFoundError when no entities are found.
func (riq *RoomInfoQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = riq.Limit(2).IDs(setContextOp(ctx, riq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roominfo.Label}
	default:
		err = &NotSingularError{roominfo.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (riq *RoomInfoQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := riq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoomInfos.
func (riq *RoomInfoQuery) All(ctx context.Context) ([]*RoomInfo, error) {
	ctx = setContextOp(ctx, riq.ctx, ent.OpQueryAll)
	if err := riq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoomInfo, *RoomInfoQuery]()
	return withInterceptors[[]*RoomInfo](ctx, riq, qr, riq.inters)
}

// AllX is like All, but panics if an error occurs.
func (riq *RoomInfoQuery) AllX(ctx context.Context) []*RoomInfo {
	nodes, err := riq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoomInfo IDs.
func (riq *RoomInfoQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if riq.ctx.Unique == nil && riq.path != nil {
		riq.Unique(true)
	}
	ctx = setContextOp(ctx, riq.ctx, ent.OpQueryIDs)
	if err = riq.Select(roominfo.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (riq *RoomInfoQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := riq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (riq *RoomInfoQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, riq.ctx, ent.OpQueryCount)
	if err := riq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, riq, querierCount[*RoomInfoQuery](), riq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (riq *RoomInfoQuery) CountX(ctx context.Context) int {
	count, err := riq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (riq *RoomInfoQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, riq.ctx, ent.OpQueryExist)
	switch _, err := riq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (riq *RoomInfoQuery) ExistX(ctx context.Context) bool {
	exist, err := riq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoomInfoQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (riq *RoomInfoQuery) Clone() *RoomInfoQuery {
	if riq == nil {
		return nil
	}
	return &RoomInfoQuery{
		config:     riq.config,
		ctx:        riq.ctx.Clone(),
		order:      append([]roominfo.OrderOption{}, riq.order...),
		inters:     append([]Interceptor{}, riq.inters...),
		predicates: append([]predicate.RoomInfo{}, riq.predicates...),
		withRooms:  riq.withRooms.Clone(),
		// clone intermediate query.
		sql:  riq.sql.Clone(),
		path: riq.path,
	}
}

// WithRooms tells the query-builder to eager-load the nodes that are connected to
// the "rooms" edge. The optional arguments are used to configure the query builder of the edge.
func (riq *RoomInfoQuery) WithRooms(opts ...func(*RoomQuery)) *RoomInfoQuery {
	query := (&RoomClient{config: riq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	riq.withRooms = query
	return riq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		RoomImageURL string `json:"room_image_url,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoomInfo.Query().
//		GroupBy(roominfo.FieldRoomImageURL).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (riq *RoomInfoQuery) GroupBy(field string, fields ...string) *RoomInfoGroupBy {
	riq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoomInfoGroupBy{build: riq}
	grbuild.flds = &riq.ctx.Fields
	grbuild.label = roominfo.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		RoomImageURL string `json:"room_image_url,omitempty"`
//	}
//
//	client.RoomInfo.Query().
//		Select(roominfo.FieldRoomImageURL).
//		Scan(ctx, &v)
func (riq *RoomInfoQuery) Select(fields ...string) *RoomInfoSelect {
	riq.ctx.Fields = append(riq.ctx.Fields, fields...)
	sbuild := &RoomInfoSelect{RoomInfoQuery: riq}
	sbuild.label = roominfo.Label
	sbuild.flds, sbuild.scan = &riq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoomInfoSelect configured with the given aggregations.
func (riq *RoomInfoQuery) Aggregate(fns ...AggregateFunc) *RoomInfoSelect {
	return riq.Select().Aggregate(fns...)
}

func (riq *RoomInfoQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range riq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, riq); err != nil {
				return err
			}
		}
	}
	for _, f := range riq.ctx.Fields {
		if !roominfo.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if riq.path != nil {
		prev, err := riq.path(ctx)
		if err != nil {
			return err
		}
		riq.sql = prev
	}
	return nil
}

func (riq *RoomInfoQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoomInfo, error) {
	var (
		nodes       = []*RoomInfo{}
		_spec       = riq.querySpec()
		loadedTypes = [1]bool{
			riq.withRooms != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoomInfo).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoomInfo{config: riq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, riq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := riq.withRooms; query != nil {
		if err := riq.loadRooms(ctx, query, nodes, nil,
			func(n *RoomInfo, e *Room) { n.Edges.Rooms = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (riq *RoomInfoQuery) loadRooms(ctx context.Context, query *RoomQuery, nodes []*RoomInfo, init func(*RoomInfo), assign func(*RoomInfo, *Room)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uuid.UUID]*RoomInfo)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(room.FieldIDInfo)
	}
	query.Where(predicate.Room(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(roominfo.RoomsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.IDInfo
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "id_info" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (riq *RoomInfoQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := riq.querySpec()
	_spec.Node.Columns = riq.ctx.Fields
	if len(riq.ctx.Fields) > 0 {
		_spec.Unique = riq.ctx.Unique != nil && *riq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, riq.driver, _spec)
}

func (riq *RoomInfoQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roominfo.Table, roominfo.Columns, sqlgraph.NewFieldSpec(roominfo.FieldID, field.TypeUUID))
	_spec.From = riq.sql
	if unique := riq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if riq.path != nil {
		_spec.Unique = true
	}
	if fields := riq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roominfo.FieldID)
		for i := range fields {
			if fields[i] != roominfo.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := riq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := riq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := riq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := riq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (riq *RoomInfoQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(riq.driver.Dialect())
	t1 := builder.Table(roominfo.Table)
	columns := riq.ctx.Fields
	if len(columns) == 0 {
		columns = roominfo.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if riq.sql != nil {
		selector = riq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if riq.ctx.Unique != nil && *riq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range riq.predicates {
		p(selector)
	}
	for _, p := range riq.order {
		p(selector)
	}
	if offset := riq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := riq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoomInfoGroupBy is the group-by builder for RoomInfo entities.
type RoomInfoGroupBy struct {
	selector
	build *RoomInfoQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (rigb *RoomInfoGroupBy) Aggregate(fns ...AggregateFunc) *RoomInfoGroupBy {
	rigb.fns = append(rigb.fns, fns...)
	return rigb
}

// Scan applies the selector query and scans the result into the given value.
func (rigb *RoomInfoGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, rigb.build.ctx, ent.OpQueryGroupBy)
	if err := rigb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomInfoQuery, *RoomInfoGroupBy](ctx, rigb.build, rigb, rigb.build.inters, v)
}

func (rigb *RoomInfoGroupBy) sqlScan(ctx context.Context, root *RoomInfoQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(rigb.fns))
	for _, fn := range rigb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*rigb.flds)+len(rigb.fns))
		for _, f := range *rigb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*rigb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := rigb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoomInfoSelect is the builder for selecting fields of RoomInfo entities.
type RoomInfoSelect struct {
	*RoomInfoQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ris *RoomInfoSelect) Aggregate(fns ...AggregateFunc) *RoomInfoSelect {
	ris.fns = append(ris.fns, fns...)
	return ris
}

// Scan applies the selector query and scans the result into the given value.
func (ris *RoomInfoSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ris.ctx, ent.OpQuerySelect)
	if err := ris.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoomInfoQuery, *RoomInfoSelect](ctx, ris.RoomInfoQuery, ris, ris.inters, v)
}

func (ris *RoomInfoSelect) sqlScan(ctx context.Context, root *RoomInfoQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ris.fns))
	for _, fn := range ris.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ris.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ris.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
