// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-service/internal/ent/usernamepassword"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UsernamePasswordCreate is the builder for creating a UsernamePassword entity.
type UsernamePasswordCreate struct {
	config
	mutation *UsernamePasswordMutation
	hooks    []Hook
}

// SetUsername sets the "username" field.
func (upc *UsernamePasswordCreate) SetUsername(s string) *UsernamePasswordCreate {
	upc.mutation.SetUsername(s)
	return upc
}

// SetPassword sets the "password" field.
func (upc *UsernamePasswordCreate) SetPassword(s string) *UsernamePasswordCreate {
	upc.mutation.SetPassword(s)
	return upc
}

// SetID sets the "id" field.
func (upc *UsernamePasswordCreate) SetID(u uuid.UUID) *UsernamePasswordCreate {
	upc.mutation.SetID(u)
	return upc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (upc *UsernamePasswordCreate) SetNillableID(u *uuid.UUID) *UsernamePasswordCreate {
	if u != nil {
		upc.SetID(*u)
	}
	return upc
}

// Mutation returns the UsernamePasswordMutation object of the builder.
func (upc *UsernamePasswordCreate) Mutation() *UsernamePasswordMutation {
	return upc.mutation
}

// Save creates the UsernamePassword in the database.
func (upc *UsernamePasswordCreate) Save(ctx context.Context) (*UsernamePassword, error) {
	upc.defaults()
	return withHooks(ctx, upc.sqlSave, upc.mutation, upc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (upc *UsernamePasswordCreate) SaveX(ctx context.Context) *UsernamePassword {
	v, err := upc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upc *UsernamePasswordCreate) Exec(ctx context.Context) error {
	_, err := upc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upc *UsernamePasswordCreate) ExecX(ctx context.Context) {
	if err := upc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (upc *UsernamePasswordCreate) defaults() {
	if _, ok := upc.mutation.ID(); !ok {
		v := usernamepassword.DefaultID()
		upc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (upc *UsernamePasswordCreate) check() error {
	if _, ok := upc.mutation.Username(); !ok {
		return &ValidationError{Name: "username", err: errors.New(`ent: missing required field "UsernamePassword.username"`)}
	}
	if v, ok := upc.mutation.Username(); ok {
		if err := usernamepassword.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "UsernamePassword.username": %w`, err)}
		}
	}
	if _, ok := upc.mutation.Password(); !ok {
		return &ValidationError{Name: "password", err: errors.New(`ent: missing required field "UsernamePassword.password"`)}
	}
	return nil
}

func (upc *UsernamePasswordCreate) sqlSave(ctx context.Context) (*UsernamePassword, error) {
	if err := upc.check(); err != nil {
		return nil, err
	}
	_node, _spec := upc.createSpec()
	if err := sqlgraph.CreateNode(ctx, upc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	upc.mutation.id = &_node.ID
	upc.mutation.done = true
	return _node, nil
}

func (upc *UsernamePasswordCreate) createSpec() (*UsernamePassword, *sqlgraph.CreateSpec) {
	var (
		_node = &UsernamePassword{config: upc.config}
		_spec = sqlgraph.NewCreateSpec(usernamepassword.Table, sqlgraph.NewFieldSpec(usernamepassword.FieldID, field.TypeUUID))
	)
	if id, ok := upc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := upc.mutation.Username(); ok {
		_spec.SetField(usernamepassword.FieldUsername, field.TypeString, value)
		_node.Username = value
	}
	if value, ok := upc.mutation.Password(); ok {
		_spec.SetField(usernamepassword.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	return _node, _spec
}

// UsernamePasswordCreateBulk is the builder for creating many UsernamePassword entities in bulk.
type UsernamePasswordCreateBulk struct {
	config
	err      error
	builders []*UsernamePasswordCreate
}

// Save creates the UsernamePassword entities in the database.
func (upcb *UsernamePasswordCreateBulk) Save(ctx context.Context) ([]*UsernamePassword, error) {
	if upcb.err != nil {
		return nil, upcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(upcb.builders))
	nodes := make([]*UsernamePassword, len(upcb.builders))
	mutators := make([]Mutator, len(upcb.builders))
	for i := range upcb.builders {
		func(i int, root context.Context) {
			builder := upcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UsernamePasswordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, upcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, upcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, upcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (upcb *UsernamePasswordCreateBulk) SaveX(ctx context.Context) []*UsernamePassword {
	v, err := upcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (upcb *UsernamePasswordCreateBulk) Exec(ctx context.Context) error {
	_, err := upcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (upcb *UsernamePasswordCreateBulk) ExecX(ctx context.Context) {
	if err := upcb.Exec(ctx); err != nil {
		panic(err)
	}
}
