// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-service/internal/ent/predicate"
	"chat-service/internal/ent/usernamepassword"
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// UsernamePasswordQuery is the builder for querying UsernamePassword entities.
type UsernamePasswordQuery struct {
	config
	ctx        *QueryContext
	order      []usernamepassword.OrderOption
	inters     []Interceptor
	predicates []predicate.UsernamePassword
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsernamePasswordQuery builder.
func (upq *UsernamePasswordQuery) Where(ps ...predicate.UsernamePassword) *UsernamePasswordQuery {
	upq.predicates = append(upq.predicates, ps...)
	return upq
}

// Limit the number of records to be returned by this query.
func (upq *UsernamePasswordQuery) Limit(limit int) *UsernamePasswordQuery {
	upq.ctx.Limit = &limit
	return upq
}

// Offset to start from.
func (upq *UsernamePasswordQuery) Offset(offset int) *UsernamePasswordQuery {
	upq.ctx.Offset = &offset
	return upq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (upq *UsernamePasswordQuery) Unique(unique bool) *UsernamePasswordQuery {
	upq.ctx.Unique = &unique
	return upq
}

// Order specifies how the records should be ordered.
func (upq *UsernamePasswordQuery) Order(o ...usernamepassword.OrderOption) *UsernamePasswordQuery {
	upq.order = append(upq.order, o...)
	return upq
}

// First returns the first UsernamePassword entity from the query.
// Returns a *NotFoundError when no UsernamePassword was found.
func (upq *UsernamePasswordQuery) First(ctx context.Context) (*UsernamePassword, error) {
	nodes, err := upq.Limit(1).All(setContextOp(ctx, upq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usernamepassword.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (upq *UsernamePasswordQuery) FirstX(ctx context.Context) *UsernamePassword {
	node, err := upq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsernamePassword ID from the query.
// Returns a *NotFoundError when no UsernamePassword ID was found.
func (upq *UsernamePasswordQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upq.Limit(1).IDs(setContextOp(ctx, upq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usernamepassword.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (upq *UsernamePasswordQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := upq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsernamePassword entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsernamePassword entity is found.
// Returns a *NotFoundError when no UsernamePassword entities are found.
func (upq *UsernamePasswordQuery) Only(ctx context.Context) (*UsernamePassword, error) {
	nodes, err := upq.Limit(2).All(setContextOp(ctx, upq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usernamepassword.Label}
	default:
		return nil, &NotSingularError{usernamepassword.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (upq *UsernamePasswordQuery) OnlyX(ctx context.Context) *UsernamePassword {
	node, err := upq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsernamePassword ID in the query.
// Returns a *NotSingularError when more than one UsernamePassword ID is found.
// Returns a *NotFoundError when no entities are found.
func (upq *UsernamePasswordQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = upq.Limit(2).IDs(setContextOp(ctx, upq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usernamepassword.Label}
	default:
		err = &NotSingularError{usernamepassword.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (upq *UsernamePasswordQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := upq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsernamePasswords.
func (upq *UsernamePasswordQuery) All(ctx context.Context) ([]*UsernamePassword, error) {
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryAll)
	if err := upq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsernamePassword, *UsernamePasswordQuery]()
	return withInterceptors[[]*UsernamePassword](ctx, upq, qr, upq.inters)
}

// AllX is like All, but panics if an error occurs.
func (upq *UsernamePasswordQuery) AllX(ctx context.Context) []*UsernamePassword {
	nodes, err := upq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsernamePassword IDs.
func (upq *UsernamePasswordQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if upq.ctx.Unique == nil && upq.path != nil {
		upq.Unique(true)
	}
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryIDs)
	if err = upq.Select(usernamepassword.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (upq *UsernamePasswordQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := upq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (upq *UsernamePasswordQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryCount)
	if err := upq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, upq, querierCount[*UsernamePasswordQuery](), upq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (upq *UsernamePasswordQuery) CountX(ctx context.Context) int {
	count, err := upq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (upq *UsernamePasswordQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, upq.ctx, ent.OpQueryExist)
	switch _, err := upq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (upq *UsernamePasswordQuery) ExistX(ctx context.Context) bool {
	exist, err := upq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsernamePasswordQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (upq *UsernamePasswordQuery) Clone() *UsernamePasswordQuery {
	if upq == nil {
		return nil
	}
	return &UsernamePasswordQuery{
		config:     upq.config,
		ctx:        upq.ctx.Clone(),
		order:      append([]usernamepassword.OrderOption{}, upq.order...),
		inters:     append([]Interceptor{}, upq.inters...),
		predicates: append([]predicate.UsernamePassword{}, upq.predicates...),
		// clone intermediate query.
		sql:  upq.sql.Clone(),
		path: upq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsernamePassword.Query().
//		GroupBy(usernamepassword.FieldUsername).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (upq *UsernamePasswordQuery) GroupBy(field string, fields ...string) *UsernamePasswordGroupBy {
	upq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsernamePasswordGroupBy{build: upq}
	grbuild.flds = &upq.ctx.Fields
	grbuild.label = usernamepassword.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Username string `json:"username,omitempty"`
//	}
//
//	client.UsernamePassword.Query().
//		Select(usernamepassword.FieldUsername).
//		Scan(ctx, &v)
func (upq *UsernamePasswordQuery) Select(fields ...string) *UsernamePasswordSelect {
	upq.ctx.Fields = append(upq.ctx.Fields, fields...)
	sbuild := &UsernamePasswordSelect{UsernamePasswordQuery: upq}
	sbuild.label = usernamepassword.Label
	sbuild.flds, sbuild.scan = &upq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsernamePasswordSelect configured with the given aggregations.
func (upq *UsernamePasswordQuery) Aggregate(fns ...AggregateFunc) *UsernamePasswordSelect {
	return upq.Select().Aggregate(fns...)
}

func (upq *UsernamePasswordQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range upq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, upq); err != nil {
				return err
			}
		}
	}
	for _, f := range upq.ctx.Fields {
		if !usernamepassword.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if upq.path != nil {
		prev, err := upq.path(ctx)
		if err != nil {
			return err
		}
		upq.sql = prev
	}
	return nil
}

func (upq *UsernamePasswordQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsernamePassword, error) {
	var (
		nodes = []*UsernamePassword{}
		_spec = upq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsernamePassword).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsernamePassword{config: upq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, upq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (upq *UsernamePasswordQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := upq.querySpec()
	_spec.Node.Columns = upq.ctx.Fields
	if len(upq.ctx.Fields) > 0 {
		_spec.Unique = upq.ctx.Unique != nil && *upq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, upq.driver, _spec)
}

func (upq *UsernamePasswordQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usernamepassword.Table, usernamepassword.Columns, sqlgraph.NewFieldSpec(usernamepassword.FieldID, field.TypeUUID))
	_spec.From = upq.sql
	if unique := upq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if upq.path != nil {
		_spec.Unique = true
	}
	if fields := upq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usernamepassword.FieldID)
		for i := range fields {
			if fields[i] != usernamepassword.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := upq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := upq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := upq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := upq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (upq *UsernamePasswordQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(upq.driver.Dialect())
	t1 := builder.Table(usernamepassword.Table)
	columns := upq.ctx.Fields
	if len(columns) == 0 {
		columns = usernamepassword.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if upq.sql != nil {
		selector = upq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if upq.ctx.Unique != nil && *upq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range upq.predicates {
		p(selector)
	}
	for _, p := range upq.order {
		p(selector)
	}
	if offset := upq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := upq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsernamePasswordGroupBy is the group-by builder for UsernamePassword entities.
type UsernamePasswordGroupBy struct {
	selector
	build *UsernamePasswordQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (upgb *UsernamePasswordGroupBy) Aggregate(fns ...AggregateFunc) *UsernamePasswordGroupBy {
	upgb.fns = append(upgb.fns, fns...)
	return upgb
}

// Scan applies the selector query and scans the result into the given value.
func (upgb *UsernamePasswordGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, upgb.build.ctx, ent.OpQueryGroupBy)
	if err := upgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsernamePasswordQuery, *UsernamePasswordGroupBy](ctx, upgb.build, upgb, upgb.build.inters, v)
}

func (upgb *UsernamePasswordGroupBy) sqlScan(ctx context.Context, root *UsernamePasswordQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(upgb.fns))
	for _, fn := range upgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*upgb.flds)+len(upgb.fns))
		for _, f := range *upgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*upgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := upgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsernamePasswordSelect is the builder for selecting fields of UsernamePassword entities.
type UsernamePasswordSelect struct {
	*UsernamePasswordQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ups *UsernamePasswordSelect) Aggregate(fns ...AggregateFunc) *UsernamePasswordSelect {
	ups.fns = append(ups.fns, fns...)
	return ups
}

// Scan applies the selector query and scans the result into the given value.
func (ups *UsernamePasswordSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ups.ctx, ent.OpQuerySelect)
	if err := ups.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsernamePasswordQuery, *UsernamePasswordSelect](ctx, ups.UsernamePasswordQuery, ups, ups.inters, v)
}

func (ups *UsernamePasswordSelect) sqlScan(ctx context.Context, root *UsernamePasswordQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ups.fns))
	for _, fn := range ups.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ups.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ups.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
