// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-service/internal/ent/usernamepassword"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// UsernamePassword is the model entity for the UsernamePassword schema.
type UsernamePassword struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password     string `json:"password,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UsernamePassword) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case usernamepassword.FieldUsername, usernamepassword.FieldPassword:
			values[i] = new(sql.NullString)
		case usernamepassword.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UsernamePassword fields.
func (up *UsernamePassword) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case usernamepassword.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				up.ID = *value
			}
		case usernamepassword.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				up.Username = value.String
			}
		case usernamepassword.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				up.Password = value.String
			}
		default:
			up.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UsernamePassword.
// This includes values selected through modifiers, order, etc.
func (up *UsernamePassword) Value(name string) (ent.Value, error) {
	return up.selectValues.Get(name)
}

// Update returns a builder for updating this UsernamePassword.
// Note that you need to call UsernamePassword.Unwrap() before calling this method if this UsernamePassword
// was returned from a transaction, and the transaction was committed or rolled back.
func (up *UsernamePassword) Update() *UsernamePasswordUpdateOne {
	return NewUsernamePasswordClient(up.config).UpdateOne(up)
}

// Unwrap unwraps the UsernamePassword entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (up *UsernamePassword) Unwrap() *UsernamePassword {
	_tx, ok := up.config.driver.(*txDriver)
	if !ok {
		panic("ent: UsernamePassword is not a transactional entity")
	}
	up.config.driver = _tx.drv
	return up
}

// String implements the fmt.Stringer.
func (up *UsernamePassword) String() string {
	var builder strings.Builder
	builder.WriteString("UsernamePassword(")
	builder.WriteString(fmt.Sprintf("id=%v, ", up.ID))
	builder.WriteString("username=")
	builder.WriteString(up.Username)
	builder.WriteString(", ")
	builder.WriteString("password=")
	builder.WriteString(up.Password)
	builder.WriteByte(')')
	return builder.String()
}

// UsernamePasswords is a parsable slice of UsernamePassword.
type UsernamePasswords []*UsernamePassword
