// Code generated by ent, DO NOT EDIT.

package ent

import (
	"chat-backend/internal/ent/authorize"
	"chat-backend/internal/ent/predicate"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AuthorizeUpdate is the builder for updating Authorize entities.
type AuthorizeUpdate struct {
	config
	hooks    []Hook
	mutation *AuthorizeMutation
}

// Where appends a list predicates to the AuthorizeUpdate builder.
func (au *AuthorizeUpdate) Where(ps ...predicate.Authorize) *AuthorizeUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetToken sets the "token" field.
func (au *AuthorizeUpdate) SetToken(s string) *AuthorizeUpdate {
	au.mutation.SetToken(s)
	return au
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (au *AuthorizeUpdate) SetNillableToken(s *string) *AuthorizeUpdate {
	if s != nil {
		au.SetToken(*s)
	}
	return au
}

// Mutation returns the AuthorizeMutation object of the builder.
func (au *AuthorizeUpdate) Mutation() *AuthorizeMutation {
	return au.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AuthorizeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AuthorizeUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AuthorizeUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AuthorizeUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AuthorizeUpdate) check() error {
	if v, ok := au.mutation.Token(); ok {
		if err := authorize.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Authorize.token": %w`, err)}
		}
	}
	return nil
}

func (au *AuthorizeUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(authorize.Table, authorize.Columns, sqlgraph.NewFieldSpec(authorize.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Token(); ok {
		_spec.SetField(authorize.FieldToken, field.TypeString, value)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AuthorizeUpdateOne is the builder for updating a single Authorize entity.
type AuthorizeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthorizeMutation
}

// SetToken sets the "token" field.
func (auo *AuthorizeUpdateOne) SetToken(s string) *AuthorizeUpdateOne {
	auo.mutation.SetToken(s)
	return auo
}

// SetNillableToken sets the "token" field if the given value is not nil.
func (auo *AuthorizeUpdateOne) SetNillableToken(s *string) *AuthorizeUpdateOne {
	if s != nil {
		auo.SetToken(*s)
	}
	return auo
}

// Mutation returns the AuthorizeMutation object of the builder.
func (auo *AuthorizeUpdateOne) Mutation() *AuthorizeMutation {
	return auo.mutation
}

// Where appends a list predicates to the AuthorizeUpdate builder.
func (auo *AuthorizeUpdateOne) Where(ps ...predicate.Authorize) *AuthorizeUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AuthorizeUpdateOne) Select(field string, fields ...string) *AuthorizeUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Authorize entity.
func (auo *AuthorizeUpdateOne) Save(ctx context.Context) (*Authorize, error) {
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AuthorizeUpdateOne) SaveX(ctx context.Context) *Authorize {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AuthorizeUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AuthorizeUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AuthorizeUpdateOne) check() error {
	if v, ok := auo.mutation.Token(); ok {
		if err := authorize.TokenValidator(v); err != nil {
			return &ValidationError{Name: "token", err: fmt.Errorf(`ent: validator failed for field "Authorize.token": %w`, err)}
		}
	}
	return nil
}

func (auo *AuthorizeUpdateOne) sqlSave(ctx context.Context) (_node *Authorize, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authorize.Table, authorize.Columns, sqlgraph.NewFieldSpec(authorize.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Authorize.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authorize.FieldID)
		for _, f := range fields {
			if !authorize.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authorize.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Token(); ok {
		_spec.SetField(authorize.FieldToken, field.TypeString, value)
	}
	_node = &Authorize{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorize.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
