// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Authorize is the predicate function for authorize builders.
type Authorize func(*sql.Selector)

// Member is the predicate function for member builders.
type Member func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// Room is the predicate function for room builders.
type Room func(*sql.Selector)

// RoomInfo is the predicate function for roominfo builders.
type RoomInfo func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UsernamePassword is the predicate function for usernamepassword builders.
type UsernamePassword func(*sql.Selector)
